import 'server-only';

import { randomUUID } from 'node:crypto';

import type {
  CoinTicker,
  PayoutRail,
  PayoutRailName,
  SavedAddress,
  WithdrawQuote,
  WithdrawalRecord,
  WithdrawalStatus,
} from '@/lib/models';

import { assertCaptcha } from './captcha';
import { getEconomy, getPayoutRails, getRates, getSiteConfig } from './config';
import {
  AppError,
  FieldValue,
  badRequest,
  bool,
  conflict,
  db,
  int,
  iso,
  isoOr,
  isServerFirebaseReady,
  now,
  str,
} from './db';
import * as d from './decimal';
import { debit } from './ledger';
import { pushNotification } from './users';

/* ============================================================================
   WITHDRAWALS
   ----------------------------------------------------------------------------
   The flow, and why each step exists:

     QUOTE     price the payout server-side and return every number the user
               will see. Nothing is computed in the browser, so nothing can be
               tampered with before submission.
     REQUEST   re-price from scratch, validate, then debit the balance INTO
               `lockedBalance` and create the withdrawal in one transaction.
     PAYOUT    an operator (or the scheduled batch) sends it. Only then does
               `lockedBalance` fall.

   THE LOCK IS THE POINT
   Tokens leave `balance` the moment a withdrawal is queued. Without that, a user
   with 5,000 tokens can queue five 5,000-token withdrawals before the first one
   settles, and the reconciliation is a manual apology. The tokens are not
   destroyed either — they sit in `lockedBalance` so a rejection can return them
   with a matching ledger row.

   IDEMPOTENCY
   `clientRequestId` is generated by the browser per submission and stored on the
   withdrawal. A retried submit finds the existing document and returns it rather
   than queueing a second payout.

   ADDRESS VALIDATION
   Format-checked per asset before anything is debited. A malformed address is
   the most common cause of a lost payout, and a rejected request costs nothing
   while a broadcast to a bad address is unrecoverable.
   ========================================================================== */

/* ---- ADDRESS FORMATS ------------------------------------------------------ */

const ADDRESS_RULES: Record<string, RegExp> = {
  BTC: /^(bc1[a-z0-9]{25,62}|[13][a-km-zA-HJ-NP-Z1-9]{25,34})$/,
  LTC: /^(ltc1[a-z0-9]{25,62}|[LM3][a-km-zA-HJ-NP-Z1-9]{26,33})$/,
  DOGE: /^[DA9][a-km-zA-HJ-NP-Z1-9]{25,34}$/,
  TRX: /^T[1-9A-HJ-NP-Za-km-z]{33}$/,
  USDT: /^(T[1-9A-HJ-NP-Za-km-z]{33}|0x[a-fA-F0-9]{40})$/,
  SOL: /^[1-9A-HJ-NP-Za-km-z]{32,44}$/,
  TON: /^([EU]Q[A-Za-z0-9_-]{46}|0:[a-fA-F0-9]{64})$/,
  BNB: /^0x[a-fA-F0-9]{40}$/,
  SHIB: /^0x[a-fA-F0-9]{40}$/,
  PEPE: /^0x[a-fA-F0-9]{40}$/,
  FLOKI: /^0x[a-fA-F0-9]{40}$/,
  BONK: /^[1-9A-HJ-NP-Za-km-z]{32,44}$/,
};

export function assertAddress(coin: CoinTicker, rail: PayoutRailName, address: string): string {
  const value = address.trim();
  if (!value) throw badRequest('Enter a payout address.', 'missing_address');

  /* FaucetPay and CWallet accept an email or username as well as an address,
     because that is how their own deposit flow works. */
  if (rail !== 'Direct') {
    const looksLikeEmail = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(value);
    const looksLikeHandle = /^[a-zA-Z0-9_.-]{3,32}$/.test(value);
    const rule = ADDRESS_RULES[coin];
    if (looksLikeEmail || looksLikeHandle || (rule && rule.test(value))) return value;
    throw badRequest(
      `That is not a valid ${rail} account. Use your ${rail} email, username, or a ${coin} address.`,
      'bad_address',
    );
  }

  const rule = ADDRESS_RULES[coin];
  if (rule && !rule.test(value)) {
    throw badRequest(`That is not a valid ${coin} address.`, 'bad_address');
  }
  return value;
}

/* ---- QUOTE --------------------------------------------------------------- */

function findRail(rails: PayoutRail[], coin: CoinTicker, rail: PayoutRailName): PayoutRail {
  const found = rails.find((r) => r.coin === coin && r.rail === rail && r.enabled);
  if (!found) throw badRequest(`${coin} payouts over ${rail} are not available right now.`, 'rail_unavailable');
  return found;
}

export interface QuoteInput {
  coin: CoinTicker;
  rail: PayoutRailName;
  /** Asset amount as a decimal string. */
  amount: string;
  /** Available token balance, so `max` can be reported. */
  balance: number;
}

export async function quoteWithdrawal(input: QuoteInput): Promise<WithdrawQuote> {
  const [rates, rails, economy] = await Promise.all([getRates(), getPayoutRails(), getEconomy()]);
  const rail = findRail(rails, input.coin, input.rail);

  const spot = rates.spot[input.coin] ?? 0;
  if (spot <= 0) throw badRequest(`No price available for ${input.coin}.`, 'no_price');

  const decimals = d.decimalsFor(input.coin);
  const amount = d.parse(input.amount);
  const fee = d.parse(rail.fee);
  const min = d.parse(rail.min);

  if (d.isZero(amount)) throw badRequest('Enter an amount.', 'zero_amount');
  if (d.lt(amount, min)) {
    throw badRequest(`Minimum for ${input.coin} over ${input.rail} is ${rail.min}.`, 'below_min');
  }

  /* Tokens are priced from the asset amount INCLUDING the fee: the user pays the
     network fee, and the site does not silently absorb it. */
  const gross = d.add(amount, fee);
  const usdValue = d.mul(gross, d.parse(spot));
  const tokenCost = d.ceilToInt(d.div(usdValue, d.parse(rates.usdPerToken)));

  /* Max is derived from the balance, going the other way, so the "Max" button
     can never produce an amount the balance cannot fund. */
  const balanceUsd = d.mul(d.parse(input.balance), d.parse(rates.usdPerToken));
  const maxAsset = d.max(0n, d.sub(d.div(balanceUsd, d.parse(spot)), fee));

  return {
    coin: input.coin,
    rail: input.rail,
    network: rail.network,
    amount: d.format(amount, decimals),
    fee: d.format(fee, decimals),
    receiveAmount: d.format(amount, decimals),
    tokenCost,
    usdValue: d.format(usdValue, 4),
    etaLabel: rail.etaLabel,
    quotedAt: new Date().toISOString(),
    min: rail.min,
    max: d.format(maxAsset, decimals),
    ...(economy ? {} : {}),
  };
}

/* ---- REQUEST ------------------------------------------------------------- */

export interface WithdrawRequestInput {
  uid: string;
  coin: CoinTicker;
  rail: PayoutRailName;
  address: string;
  amount: string;
  clientRequestId: string;
  captchaToken?: string | null;
  saveAddress?: boolean;
  addressLabel?: string;
  ip: string | null;
}

export async function requestWithdrawal(input: WithdrawRequestInput): Promise<WithdrawalRecord> {
  const [economy, site, rates] = await Promise.all([getEconomy(), getSiteConfig(), getRates()]);
  const cfg = economy.withdraw;

  if (!site.withdrawalsOpen) {
    throw new AppError('Withdrawals are paused right now. Your balance is safe.', 503, 'withdrawals_paused');
  }

  await assertCaptcha(input.captchaToken, 'withdraw', input.ip);

  if (!input.clientRequestId || input.clientRequestId.length < 8) {
    throw badRequest('Missing request id.', 'bad_request_id');
  }

  /* Replay: return the withdrawal this submission already created. */
  const prior = await db()
    .collection('withdrawals')
    .where('uid', '==', input.uid)
    .where('clientRequestId', '==', input.clientRequestId)
    .limit(1)
    .get();
  const priorDoc = prior.docs[0];
  if (priorDoc) return recordFrom(priorDoc.id, priorDoc.data() as Record<string, unknown>);

  const userSnap = await db().doc(`users/${input.uid}`).get();
  if (!userSnap.exists) throw new AppError('Account not found.', 404, 'not_found');
  const user = userSnap.data() as Record<string, unknown>;

  if (bool(user.suspended)) {
    throw new AppError(
      str(user.suspendedReason) || 'This account is suspended and cannot withdraw.',
      403,
      'suspended',
    );
  }

  const createdAt = iso(user.createdAt);
  if (createdAt) {
    const ageHours = (Date.now() - Date.parse(createdAt)) / 3_600_000;
    if (ageHours < cfg.minAccountAgeHours) {
      throw badRequest(
        `New accounts can withdraw after ${cfg.minAccountAgeHours} hours. ${Math.ceil(cfg.minAccountAgeHours - ageHours)}h to go.`,
        'account_too_new',
      );
    }
  }

  const balance = int(user.balance);
  if (balance < cfg.minBalanceTokens) {
    throw badRequest(
      `You need at least ${cfg.minBalanceTokens.toLocaleString('en-US')} tokens to withdraw.`,
      'below_min_balance',
    );
  }

  const address = assertAddress(input.coin, input.rail, input.address);

  const todayStart = new Date();
  todayStart.setUTCHours(0, 0, 0, 0);
  const todayCount = await db()
    .collection('withdrawals')
    .where('uid', '==', input.uid)
    .where('createdAt', '>=', todayStart)
    .count()
    .get();
  if (int(todayCount.data().count) >= cfg.dailyCount) {
    throw conflict(`Daily withdrawal limit reached (${cfg.dailyCount}). Resets at 00:00 UTC.`, 'daily_cap');
  }

  const quote = await quoteWithdrawal({
    coin: input.coin,
    rail: input.rail,
    amount: input.amount,
    balance,
  });

  if (quote.tokenCost > balance) {
    throw conflict(
      `That costs ${quote.tokenCost.toLocaleString('en-US')} tokens and you have ${balance.toLocaleString('en-US')}.`,
      'insufficient_balance',
    );
  }

  const usdValue = Number(quote.usdValue);
  const heldForReview = usdValue >= cfg.reviewThresholdUsd;
  const withdrawalId = randomUUID();

  /* Debit first, then create. If the create fails the debit is refunded by the
     catch below; if the order were reversed a crash between them would leave a
     payable withdrawal that nobody paid for. */
  await debit({
    uid: input.uid,
    amount: quote.tokenCost,
    source: 'withdrawal',
    label: `Withdrawal ${quote.amount} ${input.coin}`,
    refId: withdrawalId,
    idempotencyKey: `wd_${withdrawalId}`,
    lock: true,
  });

  const status: WithdrawalStatus = heldForReview ? 'HeldForReview' : 'Pending';
  const doc = {
    uid: input.uid,
    username: str(user.username, 'member'),
    countryCode: str(user.countryCode, 'XX'),
    email: str(user.email),
    coin: input.coin,
    rail: input.rail,
    network: quote.network,
    address,
    amount: quote.amount,
    fee: quote.fee,
    receiveAmount: quote.receiveAmount,
    tokenCost: quote.tokenCost,
    quotedUsdPerUnit: String(rates.spot[input.coin] ?? 0),
    usdValue: quote.usdValue,
    quotedAt: new Date(quote.quotedAt),
    clientRequestId: input.clientRequestId,
    status,
    txid: null,
    batchId: null,
    processedAt: null,
    failureReason: null,
    reviewedBy: null,
    ip: input.ip,
    createdAt: now(),
    updatedAt: now(),
  };

  try {
    await db().doc(`withdrawals/${withdrawalId}`).create(doc);
  } catch (error) {
    await refundLocked(input.uid, quote.tokenCost, withdrawalId, 'Queue failed');
    throw error;
  }

  if (input.saveAddress) {
    await saveAddress(input.uid, {
      label: input.addressLabel?.trim() || `${input.coin} ${input.rail}`,
      address,
      coin: input.coin,
      rail: input.rail,
    });
  }

  await pushNotification(input.uid, {
    icon: 'checkCircle',
    tone: heldForReview ? 'warning' : 'success',
    title: heldForReview ? 'Withdrawal under review' : 'Withdrawal queued',
    body: heldForReview
      ? `${quote.amount} ${input.coin} is held for a manual check. You will hear back within 24 hours.`
      : `${quote.amount} ${input.coin} is on its way — ${quote.etaLabel.toLowerCase()}.`,
    href: '/withdraw',
  });

  return recordFrom(withdrawalId, { ...doc, createdAt: new Date() });
}

/** Return locked tokens to the spendable balance with a matching ledger row. */
export async function refundLocked(
  uid: string,
  tokens: number,
  withdrawalId: string,
  reason: string,
): Promise<void> {
  await db().runTransaction(async (tx) => {
    const ref = db().doc(`users/${uid}`);
    const snap = await tx.get(ref);
    if (!snap.exists) return;

    tx.update(ref, {
      balance: FieldValue.increment(tokens),
      lockedBalance: FieldValue.increment(-tokens),
      updatedAt: now(),
    });

    tx.set(db().doc(`users/${uid}/claims/wdref_${withdrawalId}`), {
      source: 'refund',
      amount: tokens,
      baseAmount: tokens,
      exp: 0,
      refId: withdrawalId,
      label: `Withdrawal refunded — ${reason}`,
      bonusBps: 0,
      ip: null,
      day: new Date().toISOString().slice(0, 10),
      createdAt: now(),
      updatedAt: now(),
    });
  });
}

/* ---- READ ---------------------------------------------------------------- */

function recordFrom(id: string, data: Record<string, unknown>): WithdrawalRecord {
  return {
    id,
    coin: (str(data.coin, 'USDT') as CoinTicker),
    rail: (str(data.rail, 'FaucetPay') as PayoutRailName),
    network: str(data.network),
    address: str(data.address),
    amount: str(data.amount, '0'),
    fee: str(data.fee, '0'),
    receiveAmount: str(data.receiveAmount, str(data.amount, '0')),
    tokenCost: int(data.tokenCost),
    status: (str(data.status, 'Pending') as WithdrawalStatus),
    txid: data.txid ? str(data.txid) : null,
    at: isoOr(data.createdAt),
    processedAt: iso(data.processedAt),
    failureReason: data.failureReason ? str(data.failureReason) : null,
  };
}

export async function listWithdrawals(uid: string, limit = 25): Promise<WithdrawalRecord[]> {
  if (!isServerFirebaseReady()) return [];
  const snap = await db()
    .collection('withdrawals')
    .where('uid', '==', uid)
    .orderBy('createdAt', 'desc')
    .limit(limit)
    .get();
  return snap.docs.map((doc) => recordFrom(doc.id, doc.data() as Record<string, unknown>));
}

/* ---- SAVED ADDRESSES ----------------------------------------------------- */

export async function listAddresses(uid: string): Promise<SavedAddress[]> {
  if (!isServerFirebaseReady()) return [];
  const snap = await db()
    .collection(`users/${uid}/addresses`)
    .orderBy('createdAt', 'desc')
    .limit(20)
    .get();

  return snap.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      label: str(data.label, 'Saved address'),
      address: str(data.address),
      coin: (str(data.coin, 'USDT') as CoinTicker),
      rail: (str(data.rail, 'FaucetPay') as PayoutRailName),
      lastUsedAt: iso(data.lastUsedAt),
    };
  });
}

export async function saveAddress(
  uid: string,
  input: { label: string; address: string; coin: CoinTicker; rail: PayoutRailName },
): Promise<void> {
  /* Keyed on the address so saving the same one twice updates rather than
     duplicating the list. */
  const id = Buffer.from(`${input.coin}:${input.address}`).toString('base64url').slice(0, 60);
  await db().doc(`users/${uid}/addresses/${id}`).set(
    {
      label: input.label,
      address: input.address,
      coin: input.coin,
      rail: input.rail,
      lastUsedAt: now(),
      createdAt: now(),
      updatedAt: now(),
    },
    { merge: true },
  );
}

export async function deleteAddress(uid: string, id: string): Promise<void> {
  await db().doc(`users/${uid}/addresses/${id}`).delete();
}
